/* Fake spec-kit project index powering the SpecWiki UI kit.
   Mirrors the on-disk shape described in the spec (§2). */
window.SPECWIKI_DATA = {
  project: {
    name: "Taskify Platform",
    tagline: "A Spec Kit Project Wiki",
    isGitRepo: true,
  },
  constitution: {
    title: "Taskify Platform",
    principles: [
      { h: "I. Library-first", t: "Every feature ships as a self-contained, independently testable library before it is wired into the app. No feature logic lives only in the UI layer." },
      { h: "II. Contracts before code", t: "Every cross-boundary interface is specified in contracts/ and reviewed before implementation. The contract is the source of truth; the code conforms to it." },
      { h: "III. Test-first (NON-NEGOTIABLE)", t: "Red-Green-Refactor is enforced. Tests are written and approved against the spec, confirmed failing, then implementation begins." },
      { h: "IV. Observability", t: "Structured logging is required at every boundary. A feature is not done until its behaviour is observable in production." },
    ],
  },
  features: [
    {
      slug: "001-create-taskify",
      number: "001",
      title: "Create Taskify",
      branch: "001-create-taskify",
      status: "ready",
      modified: "3 days ago",
      modifiedSort: 3,
      files: { spec: true, plan: true, tasks: true, dataModel: true, research: true, quickstart: false },
      summary: "A Kanban-style task board where a project owner and team members move task cards across status columns, with per-card assignees and comment threads.",
      stories: [
        "As a project owner, I can create a board and seed it with the four default columns (Backlog, In Progress, Review, Done).",
        "As a team member, I can drag a card between columns and the new status persists for everyone.",
        "As any user, I can open a card to read its description and add a threaded comment.",
      ],
      requirements: [
        "The board MUST render up to 200 cards without visible lag on a 2-core machine.",
        "Card status changes MUST be reflected for all connected clients within 500ms.",
        "A deleted card MUST be recoverable from a trash view for 30 days.",
      ],
      clarifications: [
        { q: "Should card ordering within a column be manual or by created date?", a: "Manual — users drag to reorder; order persists per board." },
        { q: "Are comments editable after posting?", a: "No for v1. Comments are append-only; an edit log is out of scope." },
      ],
      tasks: [
        { id: "T001", label: "Scaffold board data model (Board, Column, Card)", done: true },
        { id: "T002", label: "Implement card CRUD library with tests", done: true },
        { id: "T003", label: "Drag-and-drop column reordering", done: true, parallel: true },
        { id: "T004", label: "Realtime sync over SignalR", done: false, parallel: true },
        { id: "T005", label: "Comment threads on cards", done: false, parallel: true },
        { id: "T006", label: "Trash + 30-day recovery view", done: false },
      ],
      contracts: ["api-spec.json", "signalr-spec.md"],
    },
    {
      slug: "002-user-authentication",
      number: "002",
      title: "User Authentication",
      branch: "002-user-authentication",
      status: "planned",
      modified: "1 week ago",
      modifiedSort: 7,
      files: { spec: true, plan: true, tasks: false, dataModel: false, research: true, quickstart: false },
      summary: "Email + OAuth sign-in with session management, so boards can be scoped to an authenticated owner and shared with named collaborators.",
      stories: [
        "As a new user, I can sign up with email and a password and receive a verification link.",
        "As a returning user, I can sign in with GitHub OAuth in one click.",
      ],
      requirements: [
        "Passwords MUST be hashed with Argon2id; plaintext MUST never be logged.",
        "Sessions MUST expire after 14 days of inactivity.",
      ],
      clarifications: [],
      tasks: [],
      contracts: ["auth-api.json"],
    },
    {
      slug: "003-realtime-presence",
      number: "003",
      title: "Realtime Presence",
      branch: "003-realtime-presence",
      status: "draft",
      modified: "2 weeks ago",
      modifiedSort: 14,
      files: { spec: true, plan: false, tasks: false, dataModel: false, research: false, quickstart: false },
      summary: "Show avatars of collaborators currently viewing a board and a live cursor for whoever is dragging a card.",
      stories: [
        "As a collaborator, I can see who else is viewing the board right now.",
      ],
      requirements: [
        "Presence MUST update within 1s of a user opening or closing the board.",
      ],
      clarifications: [],
      tasks: [],
      contracts: [],
    },
    {
      slug: "004-csv-export",
      number: "004",
      title: "CSV Export",
      branch: "004-csv-export",
      status: "implemented",
      modified: "yesterday",
      modifiedSort: 1,
      files: { spec: true, plan: true, tasks: true, dataModel: true, research: false, quickstart: true },
      summary: "Export any board to a CSV of cards with columns for status, assignee, and last-modified, for use in spreadsheets and reporting.",
      stories: [
        "As a project owner, I can download the current board as a CSV file.",
      ],
      requirements: [
        "Export MUST stream so boards of any size complete without holding the full file in memory.",
      ],
      clarifications: [],
      tasks: [
        { id: "T001", label: "Define CSV column schema", done: true },
        { id: "T002", label: "Streaming CSV writer with tests", done: true, parallel: true },
        { id: "T003", label: "Download button + progress toast", done: true },
      ],
      contracts: [],
    },
  ],
  recentChanges: [
    { file: "004-csv-export/tasks.md", when: "yesterday", feature: "CSV Export", slug: "004-csv-export" },
    { file: "001-create-taskify/spec.md", when: "3 days ago", feature: "Create Taskify", slug: "001-create-taskify" },
    { file: "001-create-taskify/plan.md", when: "3 days ago", feature: "Create Taskify", slug: "001-create-taskify" },
    { file: "002-user-authentication/research.md", when: "1 week ago", feature: "User Authentication", slug: "002-user-authentication" },
    { file: "003-realtime-presence/spec.md", when: "2 weeks ago", feature: "Realtime Presence", slug: "003-realtime-presence" },
  ],
};
